server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#ensure all the logs are published to zipkin
management:
  tracing:
    sampling:
      probability: 1.0